### ISSUE TITLE
无法启用插件，因为它引起了一个致命错误（fatal error）。

### ISSUE THREAD

**Issue by x7peeps** [louie-senpai/PoiPlayer#13]
我的安装过程是在git下载zip，wp中直接手动上传安装的。启用插件的时候报这个错误：
> Fatal error: Cannot redeclare class Metowolf\Meting in .../wp-content/plugins/PoiPlayer-master/inc/api/Meting.php on line 15
结果发现这文件git上的版本竟然没闭合。。
![image](https://user-images.githubusercontent.com/9640837/35657650-877ed53c-0738-11e8-8848-56f63102a174.png)
尝试在结尾添加?>
![image](https://user-images.githubusercontent.com/9640837/35657730-fa07e18e-0738-11e8-9b4b-e1e0328bb242.png)
发现还是报错，看到这个报错不能重定义class Metowolf\Meting ，找了一下源文件只有一处定义。于是想起我还开着另外一个插件。关闭另一个插件，启动成功。
![image](https://user-images.githubusercontent.com/9640837/35657912-dfc293f4-0739-11e8-8fb9-455519c64486.png)

**Comment by louie-senpai** [comment]
@XTpeeps 不能同时启用两个音乐插件。

**Comment by x7peeps** [comment]
@louie-senpai  已经解决了。
