### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by PaSSw0rds** [louie-senpai/PoiPlayer#3]
Fatal error: Cannot redeclare class Metowolf\Meting in /alidata/www/phpwind/wp-content/plugins/PoiPlayer-master/inc/api/Meting.php on line 12

**Comment by FatDoge** [comment]
Please update your PHP version.

**Comment by x7peeps** [comment]
看看#13issues， 如果之前启用了类似的网易音乐类的插件，关闭后重启启动即可。
