### ISSUE TITLE
播放器直接打不开了

### ISSUE THREAD

**Issue by LiarOnce** [louie-senpai/PoiPlayer#8]
![](https://i.loli.net/2017/12/11/5a2e1841c2e73.png)
这儿点了无数次了。

链接：[https://www.liaronce.win](https://www.liaronce.win)

**Comment by louie-senpai** [comment]
@LiarOnce 貌似JS文件没载入，你看下是不是和其他的冲突了。

**Comment by LiarOnce** [comment]
@louie-senpai JS确实没有载入，但是我不知道是哪里冲突了

**Comment by LiarOnce** [comment]
@louie-senpai 我发现问题了，是因为我取消了 WordPress 自带的 JQuery 定义导致。
```php
if ( !is_admin() ) { // 后台不禁止
function my_init_method() {
wp_deregister_script('jquery'); // 取消原有的 jquery 定义
}
add_action('init', 'my_init_method');
}
wp_deregister_script('l10n');
```
虽然注释掉就解决了，但问题是这样就会导致 JQuery 重复加载（主题也有一个）
所以我自己修改了`inc/music.php`，将第 6 行和第 7 行的 ```array(`jquery`)```改掉了，于是变成：
```php
wp_enqueue_script('poi-libs', POI_URL . '/build/js/player-base.min.js',  array() , POI_VERSION ,true);
wp_enqueue_script('poi-player', POI_URL . '/build/js/poi.min.js', array() , POI_VERSION ,true);
```

**Comment by louie-senpai** [comment]
@LiarOnce 可以，能使用就没问题了。
