### ISSUE TITLE
如何设置网易云专辑ID？

### ISSUE THREAD

**Issue by dreamCirno** [louie-senpai/PoiPlayer#9]
我找了半天了，还是找不到该再哪里设置ID，可以详细的说一下流程吗？

**Comment by dreamCirno** [comment]
是将文件放至PHP网页文件夹里，通过localhost去访问吗？还是修改后台代码？

**Comment by ReZeroS** [comment]
登录 wp-admin 就是你的WordPress 后台， 会有 PoiPlayer设置的tab选项，点进去会有选项，（id去网易云web 找到你要的歌单， 然后看歌单页面 的url， 会看到id） 填上就行了

**Comment by dreamCirno** [comment]
谢谢你的回答，但是我在插件中，找不到PoiPlayer的设置。只看见了停用选项。我该如何做？

**Comment by ReZeroS** [comment]
蛤？ PoiPlayer 激活插件后应该是一个单独的tab设置选项（就是你登录后台的主界面就可以看到）， 而不是在plugin（不需要再点进plugin，找到插件啥的）中设置吧

**Comment by dreamCirno** [comment]
谢谢你的帮助，我一直没有注意到，在仪表盘的下方是PoiPlayer的单独设置界面。第一次使用WordPress插件，我还以为要去找后台源码，去修改呢。谢谢你的帮助！
